version: "3.8"
services:
  qbittorrent:
    build: .
    image: ixuewen/qbittorrent
    container_name: qbittorrent-docker
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/docker-volume/qBittorrent:/qBittorrent
    environment:
      - PORT=8081
