version: "3.8"
services:
  transmission:
    build: .
    image: ixuewen/transmission
    container_name: transmission-docker
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/docker-volume/transmission:/transmission
    environment:
      - PORT=9091
      - USERNAME=admin
      - PASSWORD=adminadmin
